### ISSUE TITLE
OpenIDConnectSettings problem

### ISSUE THREAD

**Issue by havana7** [damienbod/AspNetCoreOpeniddict#20]
When starting the application I get this error:

An unhandled exception occurred while processing the request.
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Microsoft.IdentityModel.Json.JsonTextReader.ParseValue ()

InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
Microsoft.IdentityModel.Protocols.ConfigurationManager <T> .GetConfigurationAsync (CancellationToken cancel)

This is the appsetting.json file

`  "OpenIDConnectSettings": {
    "Authority": "https://localhost:44348",
    "ClientId": "blazorcodeflowpkceclient",
    "ClientSecret": "3B104FC1-E63C-4DA4-858F-C572A68DB041"
  }`

**Comment by damienbod** [comment]
just checked this locally and I don't have this problem. This used happens when you have a syntax error in your config file. Can you check this again?
 
do you have the latest version as well? 

Greetings Damien

**Comment by havana7** [comment]
Yes I have the updated Main version.

I am referring to the Blazor.BFF.OpenIddict project

I set it as a startup project and only changed the authority port in the
appsetting.json file

Il giorno mer 12 gen 2022 alle ore 18:05 damienbod ***@***.***>
ha scritto:

**Comment by damienbod** [comment]
Do you start the Blazor.BFF.OpenIddict.Server project?

**Comment by havana7** [comment]
Yes, the server project

**Comment by damienbod** [comment]
Hi @havana7  I tried this and had no problems:

- clean clone of the repo
- opened the solution using Visual Studio 2022
- Started the OpenIddictServer at https://localhost:44395/
- Started the ResourceServer API at https://localhost:44390
- Start Blazor.BFF.OpenIddict.Server at https://localhost:44348/

had no problems and made no changes

What do you do differently?

Greetings Damien

**Comment by havana7** [comment]
Ok, it works!
So you need to start both OpenIddictServer and Blazor.BFF.OpenIddict.Server at a minimum.

From the Blazor.BFF.OpenIddict.Server project the user cannot manage his own profile.

Is it possible to integrate authentication with Goggle, Facebook, etc?

Thank you
