### ISSUE TITLE
How can I get UserId?

### ISSUE THREAD

**Issue by havana7** [damienbod/AspNetCoreOpeniddict#21]
Is it possible to obtain the UserId together with the UserName?

**Comment by damienbod** [comment]
Hi @havana7 yes, you can set the name claim as required. You can also map the claim to anything you want. This is done in the Startup.

See these docs:

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-6.0

Greetings Damien

**Comment by havana7** [comment]
I'm sorry, but I'm very confused.

I added this code on the Blazor.Server side startup:
`options.ClaimActions.MapUniqueJsonKey("userid", "userid");`
 but on the Blazor.Client I can't retrieve the UserId.

Can you give me some indication?

Thanks again.

**Comment by damienbod** [comment]
Ah, this looks like a mistake from me, I'll check. The userid claim will be mapped if it exists. I guess this claim does not get returned from the IDP and then nothing to map and so it does not exist on the client. If you add a breakpoint on the user controller, you can see what claims are available. If you require extra claims, you can add these to the IDP, or extend the claims in the Blazor server and the  claims can be used on the client.

**Comment by havana7** [comment]
Hi Damien,
I solved it by uncommenting this part in the UserControl
`foreach (var claim in claimsPrincipal.Claims.Except(nameClaims))
{
    claims.Add(new ClaimValue(claim.Type, claim.Value));
}`

I got the userId in the razor like this:
`ClaimsIdentity claimsIdentity = user.Identity as ClaimsIdentity;
Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
var userId = claim.Value;`

What do you think?
