### ISSUE TITLE
Guidance

### ISSUE THREAD

**Issue by NetDefender** [damienbod/AspNetCoreOpeniddict#38]
Is it possible to call from the Blazor Client (through HttpClient) to the Resource Server if you are authenticated with the cookie?
I tried but it refuses to authenticate. If i remove the Authorize in the resource server it works as expected, and the aspnet cookie is in the headers.

**Comment by NetDefender** [comment]
Callign GetTokenAsync does the trick.

**Comment by damienbod** [comment]
@NetDefender Thanks for the update, glad you got it working
